---
title: "Mini-Project 3"
output: 
  html_document:
    code_folding: hide
---

```{r message = FALSE, echo = FALSE, warning = FALSE}

#Opening Libraries

library(tidyverse)
library(macleish)
library(sf)
library(proj4)
library(leaflet)
library(ggplot2)
library(rgdal)
library(dplyr)
```

```{r message = FALSE, warning = FALSE}

#Map with Contours (for reference)

macleish_map <- leaflet() %>%
  addTiles() %>%
  addMarkers(~lat, ~lon)
  addPolylines(data = pluck(macleish_layers, "contours_3m"), weight = 2) %>%
  addPolylines(data = pluck(macleish_layers, "contours_30ft"), weight = 2, color = "red")

macleish_map
```

```{r}
#Isolating the "trails" Layer

macleish_trails <- pluck(macleish_layers[["trails"]])
```

```{r}
#cleaning up the macleish trails Table 
macleish_trails2 <- macleish_trails %>%
  st_join(macleish_layers$contours_3m)

```
  

```{r}
#Finding the average elevation of each trail

porc_trail <- macleish_trails2 %>%
  filter(name == "Porcupine Trail") %>%
  select(name, ELEV_FT, Shape_Leng, geometry) %>%
  mutate(elev_gain = max(ELEV_FT) - min(ELEV_FT)) %>%
  mutate(classification = sqrt((elev_gain * Shape_Leng) *2)) %>%
  st_transform(4326)

western_loop <- macleish_trails2 %>%
  filter(name == "Western Loop") %>%
  select(name, ELEV_FT,Shape_Leng, geometry) %>%
  mutate(elev_gain = max(ELEV_FT) - min(ELEV_FT)) %>%
  mutate(classification = sqrt((elev_gain * Shape_Leng) *2)) %>%
  st_transform(4326)


poplar_hill <- macleish_trails2 %>%
  filter(name == "Poplar Hill Road") %>%
  select(name, ELEV_FT,Shape_Leng, geometry) %>%
  mutate(elev_gain = max(ELEV_FT) - min(ELEV_FT)) %>%
  mutate(classification = sqrt((elev_gain * Shape_Leng) *2)) %>%
  st_transform(4326)


vernal_loop <- macleish_trails2 %>%
  filter(name == "Vernal Pool Loop") %>%
  select(name, ELEV_FT,Shape_Leng, geometry) %>%
  mutate(elev_gain = max(ELEV_FT) - min(ELEV_FT)) %>%
  mutate(classification = sqrt((elev_gain * Shape_Leng) *2)) %>%
  st_transform(4326)



eastern_loop <- macleish_trails2 %>%
  filter(name == "Eastern Loop") %>%
  select(name, ELEV_FT,Shape_Leng, geometry) %>%
  mutate(elev_gain = max(ELEV_FT) - min(ELEV_FT)) %>%
  mutate(classification = sqrt((elev_gain * Shape_Leng) *2)) %>%
  st_transform(4326)


entry_trail <-macleish_trails2 %>%
  filter(name == "entry trail") %>%
  select(name, ELEV_FT,Shape_Leng, geometry)  %>%
  mutate(elev_gain = max(ELEV_FT) - min(ELEV_FT)) %>%
  mutate(classification = sqrt((elev_gain * Shape_Leng) *2)) %>%
  st_transform(4326)


  
```




```{r}
#Making new trails dataset to add markers to map

x <- st_intersection(
  pluck(macleish_layers, "trails"), 
  pluck(macleish_layers, "contours_30ft")
)

western <- filter(x, name == "Western Loop")

western_pts <- western %>% 
  st_cast("MULTIPOINT") %>% 
  st_cast("POINT")

 markers_map <- leaflet() %>%
  addTiles() %>%
  addMarkers(data = st_cast(x, "POINT"), popup = ~name)

```

```{r}
#Wrangling data to put markers on leaflet trails map

trail_markers <- st_intersection(
  pluck(macleish_layers, "trails"), 
  pluck(macleish_layers, "contours_30ft")
) %>%
  drop_na()
```


```{r}
#Making leaflet trails Map

trails_map <- leaflet() %>%
  addTiles() %>%
  addMarkers(data = st_cast(trail_markers, "POINT"), popup = ~name) %>%
  #addPolylines(data = pluck(macleish_layers, "contours_3m"), weight = 1, color = "red") %>%
  addPolylines(data = porc_trail, weight = 2, color = "blue") %>%
  addPolylines(data = western_loop, weight = 2, color = "black") %>%
  addPolylines(data = poplar_hill, weight = 2, color = "blue") %>%
  addPolylines(data = vernal_loop, weight = 2, color = "green") %>%
  addPolylines(data = eastern_loop, weight = 2, color = "blue") %>%
  addPolylines(data = entry_trail, weight = 2, color = "green") %>%
  addMarkers(data = porc_trail, popup = ~point) %>%
  addLegend("bottomright", 
            title = "Trail Difficulty",
            colors = c("green", "blue", "black"),  
            labels = c("Easy", "Moderate", "Difficult"), 
            opacity = 1) 
```

